### PR TITLE
Sprint1 issue9 erickjperez

### PR DESCRIPTION
**Pull request by erickjperez**
Added the  server routes to the different pages we will need for this sprint (pages include page for video lecture and place for teachers to submit their videos). Also gave readme files throughout that lay out just what most things are. How to run my repository can be found under the FlippedTech folder and in the README.md file

### CODE REVIEW

**Review by tacoury — CHANGES_REQUESTED** [review]
I was unable to run the program with the given instructions in the README regarding node app.js. Following those, I get the command not found error. There might be another step I need to take, but I am unsure what it exactly is.

**Comment by erickjperez** [comment]
Updated the readme file. I forgot you needed to download node.js  in order to run the server. In the readme, I have included a link for you to run to download it. After that, just follow the directions listed to get it to work

**Review by tacoury — DISMISSED** [review]
All looks good, and functions the way it should.

**Review by nakasoori — DISMISSED** [review]
Looks good. I will make some changes later to work with the database. Most likely will be using PostgreSQL as the database language and bcrypt, cors, and knex in our node files.

**Pull request merged**
