### PR TITLE
Sprint1-issue10videoembedpage

### LINKED ISSUE #10: Page that embeds video for lecture as well as description about lecture
This page should be a template page that will be taking a respective video link and description of the lecture and is able to output it onto the page. Must be able to take different links and descriptions and output it on the page

### PR DESCRIPTION
**Pull request by jmmiller775**
-added title, description, and video to the lecture page
-added comments to the doc specifying dummy data
-resolves #10

### CODE REVIEW

**Review by erickjperez — CHANGES_REQUESTED** [review]
Runs without errors but need to edit the description to take javascript like you did with the title and video link

**Review by erickjperez — COMMENTED** [review]
Edit was made to use description based on something sent through. Code is well commented and does what it's supposed to. Will leave open for others to review

**Review by tacoury — COMMENTED** [review]
Code is consistent and well commented. Runs the way it should with no errors. Wait for final reviewer

**Review by nakasoori — APPROVED** [review]
Looks good. Runs like planned.

**Review by erickjperez — APPROVED** [review]

**Pull request merged**
