### PR TITLE
Resolves 75, added date and time picker

### PR DESCRIPTION
**Pull request by tacoury**
I added a date and time picker to the lecture upload page. Run the following commands before running npm start:
npm install react-datepicker
npm install ajv-keywords@3.1.0 ajv@^6.0.0
npm install react-datepicker@1.4.1 moment@^2.20.0
npm install rc-time-picker

### CODE REVIEW

**Review by erickjperez — DISMISSED** [review]
Ran the commands before running "npm start" and the program does not perform as expected. When ran, the date and time picker does not show. The page is the same as before this pull request where you had to manually enter the date and time

**Comment by nakasoori** [comment]
Date picker and time picker shows as intended for me.

**Review by nakasoori — APPROVED** [review]
Displays as intended

**Comment by erickjperez** [comment]
resolved in separate request that has already been pulled into develop

**Pull request closed without merging**
