### PR TITLE
Sprint2 issue40 tacoury

### PR DESCRIPTION
**Pull request by tacoury**
This is the frontend for the admin upload page.

### CODE REVIEW

**Review by nakasoori — CHANGES_REQUESTED** [review]
Looks good. Fix typo for "Description of Lecture:" first though before merging.

**Review by jmmiller775 — COMMENTED** [review]
Code looks good and performs as expected! Later on we'll have to change the 'link to lecture vid' part to be just video ID once we get API set-up. Looks awesome for now though!

**Review by nakasoori — DISMISSED** [review]
Looks good

**Review by nakasoori — APPROVED** [review]
Fixed merge errors

**Pull request merged**
