### PR TITLE
Sprint5 issue72/72 snakanishi/erickperez

### PR DESCRIPTION
**Pull request by nakasoori**
Added new routes for adding lecture page, admin can now add a new lecture and reroutes back to the lecture list, student can see lectures, lectures reflect the correct description and YouTube video, implemented the new YouTube API with current branch(previously not merged).

### CODE REVIEW

**Comment by nakasoori** [comment]
NOTE: You may have to install react-youtube

**Comment by nakasoori** [comment]
Adding comment sections to individual lectures, do not merge yet

**Review by tacoury — CHANGES_REQUESTED** [review]
I am able to add a lecture from the admin side and it populates on both the student and admin side with the correct info and video. The lectures are persistent as well. I also like how the comments are now populated to the top of the list. The only issue is the comments are the same for each lecture, and thus when a new lecture is added it includes all of the comments in the database. Each lecture needs its own set of comments.

**Comment by erickjperez** [comment]
resolves #74 #73 #72

**Review by tacoury — APPROVED** [review]

**Pull request merged**
