### PR TITLE
Sprint2 issue46 jmiller

### PR DESCRIPTION
**Pull request by jmmiller775**
Embeds video using react code. Takes care of #46

### CODE REVIEW

**Comment by nakasoori** [comment]
I don't see where in the main code you run the test to see your page. Update index.js to render your Youtube component.

**Comment by jmmiller775** [comment]
Just updated index.js file so it now works with npm start

**Review by erickjperez — COMMENTED** [review]
Code looks good. Runs as expected. Leaving open for others to review as well

**Review by nakasoori — DISMISSED** [review]
Looks good now. Nicely embedded

**Review by nakasoori — APPROVED** [review]
Merged conflicts fixed. Works well

**Pull request merged**
