### PR TITLE
Added a home page in React that looks the same as before

### PR DESCRIPTION
**Pull request by nakasoori**

### CODE REVIEW

**Comment by nakasoori** [comment]
To test the project, go to "/flippedtech " directory and run the command "npm start"

**Comment by nakasoori** [comment]
Also, run "npm install" before "npm start"

**Review by jmmiller775 — COMMENTED** [review]
Looks good. The code works as specified and implements the former page in react. Nice job!

**Review by erickjperez — COMMENTED** [review]
After running npm install, the code runs perfectly and the output is as expected. Looks very similar to our original home page. Nice!

**Review by jmmiller775 — APPROVED** [review]
Looks good! Ready to merge

**Pull request merged**
