### PR TITLE
Added Routes, some style changes

### PR DESCRIPTION
**Pull request by nakasoori**
Like last time, run "npm install" first before doing "npm start". Sorry about color scheme

### CODE REVIEW

**Review by erickjperez — DISMISSED** [review]
Code runs as expected. Fantastic job seth. My only critique is that you add more comments. Specifically to the sign in pages. All else is good and self explanatory

**Review by jmmiller775 — COMMENTED** [review]
Looks awesome! Excellent work Seth! That sign in interface looks awesome.

**Review by tacoury — COMMENTED** [review]
Code is consistent and runs as expected. The new comments add necessary clarity. Looks good to go.

**Review by jmmiller775 — COMMENTED** [review]
Code is consistent and performs as described! Looks really good. Good work!

**Review by erickjperez — COMMENTED** [review]
Great Work Seth. Nice comments and code still does what it should

**Review by jmmiller775 — COMMENTED** [review]
Looks great Seth! I really like the sign in interface. The code is commented well and runs as described.

**Review by tacoury — COMMENTED** [review]
Nice job; consistent, well commented, and clear

**Review by erickjperez — APPROVED** [review]

**Pull request merged**
